fields:
    - name: url
      required: True
      viewby: True

    - name: title
      required: True

    - name: body
      required: True
      widget:
        type: TextArea
        css_class: markitup

    - name: template
      widget:
        type: SelectChoice
        options: 
          - [content.html,Default]
          - [home.html,Home]
          - [gallery.html,Gallery]
          - [visit.html,Visit]

    - name: metadata
      type: Structure

    - name: metadata.title
    - name: metadata.description
    - name: metadata.keywords

    - name: sort
      type: Integer


views:
- type: all
- type: all_count
- name: by_segments
  map: |
    function(doc) {
      if (doc.model_type == 'page') {
        var segments = doc.url.split('/');
        emit(segments.slice(1), {"id":doc._id,"title":doc.title});
      }
    }


