fields:
  - name: code
    required: True

  - name: photo
    type: Reference
    attr:
      refersto: photo/all_data
    widget:
      label: '%(ref)s'
      sort: True

  - name: title
    required: True

  - name: information
    widget:
      type: TextArea
      css_class: markitup

  - name: edition

  - name: show
    type: Boolean

  - name: available
    type: Boolean

  - name: type
    widget:
      type: SelectChoice
      options:
        - [Print,Print]
        - [Greetings Card,Greetings Card]
        - [Book,Book]
        - [Calendar,Calendar]


  - name: pricing
    type: Sequence
    attr: 
      type: Structure

  - name: pricing.*.option
    required: True

  - name: pricing.*.label
    required: True

  - name: pricing.*.price
    type: Float
    required: True

  - name: pricing.*.postage
    type: Float
    required: True


metadata:
  indexes:
     - name: title
     - name: code
       type: exact
     - name: location_label
       var: photo.location_category.*.data.label
     - name: location
       var: photo.location_category.*.path
       type: exact
     - name: subject_label
       var: photo.subject_category.*.data.label
     - name: subject
       var: photo.subject_category.*.path
       type: exact
  templates:
    items-table:
      - name: code
      - label: Photo
        name: photo.photo
        value: "<img src=\"/filehandler/${item['photo']['ref']}?size=50x50\" />"
      - name: title
      - name: edition
      - name: type

views:
- type: all
- type: all_count
- name: by_master_photo
  map: |
    function(doc) { 
      if (doc.model_type == 'product') { emit(doc.photo.ref, null); } 
    }
- name: by_code
  map: |
    function(doc) { 
       if (doc.model_type == 'product') { emit(doc.code, null); } 
    }
- name: by_type_and_subject_category
  map: |
    function(doc) {
      if (doc.model_type == 'product' && doc.photo.photographer == 'Joe Cornish') {
        for (c in doc.photo.subject_category) {
          var segments = doc.photo.subject_category[c]['path'].split('.');
          segments.unshift(doc.type);
          emit(segments, doc._id);
        } 
      }
    }

- name: by_type_and_location_category
  map: |
    function(doc) {
      if (doc.model_type == 'product' && doc.photo.photographer == 'Joe Cornish') {
        for (c in doc.photo.location_category) {
          var segments = doc.photo.location_category[c]['path'].split('.');
          segments.unshift(doc.type);
          emit(segments, doc._id);
        } 
      }
    }

